export const JOB_TITLE_VALUES = {
    FRONTEND: "frontend",
    BACKEND_DEVELOPER: "backend",
    DESIGNER: "designer",
    QA: "qa"
}

export const JOB_TITLE_LABELS = {
    FRONTEND: "Frontend developer",
    BACKEND_DEVELOPER: "Backend developer",
    DESIGNER: "Designer",
    QA: "QA"
}

export const JOB_TITLE_VALUE_TO_LABEL_MAP = {
    [JOB_TITLE_VALUES.FRONTEND]: JOB_TITLE_LABELS.FRONTEND,
    [JOB_TITLE_VALUES.BACKEND_DEVELOPER]: JOB_TITLE_LABELS.BACKEND_DEVELOPER,
    [JOB_TITLE_VALUES.DESIGNER]: JOB_TITLE_LABELS.DESIGNER,
    [JOB_TITLE_VALUES.QA]: JOB_TITLE_LABELS.QA
}

export const JOB_TITLE_OPTIONS = [
    { label: JOB_TITLE_LABELS.FRONTEND, value: JOB_TITLE_VALUES.FRONTEND },
    { label: JOB_TITLE_LABELS.BACKEND_DEVELOPER, value: JOB_TITLE_VALUES.BACKEND_DEVELOPER },
    { label: JOB_TITLE_LABELS.DESIGNER, value: JOB_TITLE_VALUES.DESIGNER },
    { label: JOB_TITLE_LABELS.QA, value: JOB_TITLE_VALUES.QA }
]